routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
	return view('thankyou');
    return redirect('/home');
});


Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::middleware(['auth'])->group(function () {
	
	Route::post('/mark-as-read', 'MessageController@markAsRead');	

	Route::post('/messages/{user}', 'MessageController@send');	
	Route::get('/users/messages', 'UserController@getUserMessages')->name('users.message');
	Route::post('/leads/get', 'LeadController@get')->name('lead.get');
	Route::post('/leads/feedback', 'LeadController@feedback');
	Route::post('/leads/export', 'LeadController@export');
	Route::post('/users/export', 'UserController@export');
	
	Route::middleware(['admin'])->group(function () {
		Route::get('/lead-score/{lead}', 'LeadController@showQualityScoreLog');
		
		Route::post('/mark-user-message-as-read/{user}', 'MessageController@markUserMessageAsRead');	

		Route::post('/leads/register/{lead}/{user}', 'LeadController@assignLead');
		Route::get('/leads/assign', 'LeadController@showAssignForm');
		Route::get('/users/get', 'UserController@get')->name('users.get');
		Route::post('/users/information-visibility/{user}', 'UserController@changeUserInformationVisibilityStatus');
		Route::get('/messages', 'MessageController@index')->name('message');

		Route::resource('users', 'UserController');
	});
});
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );

app/User.php
<?php

namespace App;

use App\Country;
use App\Message;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'funds',
        'total_leads',
        'daily_leads',
        'action_price',
        'quality_score_target_from',
        'quality_score_target_to',
        'is_admin',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function countries(){
        
        return $this->belongsToMany(Country::class);
    }

    public function messages(){
        
        return $this->hasMany(Message::class,'to');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Auth;
use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\StoreUserRequest;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = auth()->user()->with('leads');
        return view('user.index')->with(['user' => $user]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function get()
    {
        $users = User::where('is_admin',false)->with(['countries'=>function($query){
            $query->select('name');
        }])->get();
        return datatables()->of($users)->toJson();
    }

    public function export(Request $request){

       $data = $request->validate([
            'export-lead-from' => 'required',
            'export-lead-to' => 'required',
        ]);

        $from = $data['export-lead-from'];
        $to = $data['export-lead-to'];

        $users = User::where('is_admin',false)->with(['countries'=>function($query){
            $query->select('name');
        }])->get(); 

        return view('user.export')->with([
            'users' => $users
        ]);
    }

    public function getUserMessages(){
        $admin = User::where('is_admin',1)->first();
        $messages = Auth::user()->messages()->paginate(4);
        return view('user.message')->with(['admin'=>$admin ,'messages' => $messages]);
    }

    public function changeUserInformationVisibilityStatus(Request $request, User $user){
        $data =  $request->validate([
        'status' => 'required',
        ]);

        $user->can_see_all_information = (int)$data['status'];
        $user->save();
        return ['success' => 200];
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\StoreUserRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request){
        
        $request->registerUser();
      
        return ['success' => 201];
    }

    /**
     * Display the specified resource.
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
       return view('user.show')->with(['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\StoreUserRequest  $request
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUserRequest $request, User $user)
    {
        $request->updateUser($user);
        
        return ['success' => 204];
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        
        <div class="alert alert-success" style="display:none" id="alert" role="alert">
        </div>
        <div class="alert alert-danger" style="display:none" id="error" role="alert">
        </div>
        <div class="col-md-12">
            <form class="form"  action="{{route('users.create')}}">
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" id="name" value="">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" value="" id="email">
                </div>
                <div class="form-group">
                    <label for="password">{{ __('Password') }}</label>
                    
                    <input id="password" type="password" class="form-control" name="password" required>
                    
                </div>
                <div class="form-group">
                    <label for="password-confirm">{{ __('Confirm Password') }}</label>
                    
                    <input id="password_confirmation" type="password" class="form-control" name="password_confirmation" required>
                    
                </div>  

                <div class="form-group">
                    <label for="countries">Countries</label>
                    
                    <select id="countries" class="form-control" multiple>
                        @foreach($countries as $country)
                            <option value="{{$country->id}}">{{$country->name}}</option>
                        @endforeach
                    </select>
                </div>
       

                <div class="form-group">
                    <label for="name">Phone:</label>
                    <input type="text" class="form-control" value="" id="phone">
                </div>
                
                <div class="form-group">
                    <label for="funds">Funds:</label>
                    <input type="number" class="form-control" value="" id="funds">
                </div>
                <div class="form-group">
                    <label for="total_leads">Total Leads:</label>
                    <input type="number" class="form-control" value="" id="total_leads">
                </div>
                
                <div class="form-group">
                    <label for="daily_leads">Daily Leads:</label>
                    <input type="number" class="form-control" value="" id="daily_leads">
                </div>
                
                <div class="form-group">
                    <label for="action_price">Action Price:</label>
                    <input type="number" class="form-control" value="" id="action_price">
                </div>
                <div class="form-group">
                    <label for="quality_score_target_from">Targeted Quality Score From:</label>
                    <input type="text" class="form-control" value="" id="quality_score_target_from">
                </div>
                
                <div class="form-group">
                    <label for="quality_score_target_to">Targeted Quality Score To:</label>
                    <input type="text" class="form-control" value="" id="quality_score_target_to">
                </div>
                <button type="button" id="create-user" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {

     $('#countries').select2();

    $("#alert").css('display', 'none');
    $("#create-user").click(function(e) {
        var id = $("#user_id").val();
        var name = $("#name").val();
        var email = $("#email").val();
        var phone = $("#phone").val();
        var funds = $("#funds").val();
        var countries = $("#countries").val();
        var total_leads = $("#total_leads").val();
        var daily_leads = $("#daily_leads").val();
        var daily_leads = $("#daily_leads").val();
        var action_price = $("#action_price").val();
        var password = $("#password").val();
        var password_confirmation = $("#password_confirmation").val();
        var quality_score_target_from = $("#quality_score_target_from").val();
        var quality_score_target_to = $("#quality_score_target_to").val();

        var data = {
            name: name,
            email: email,
            phone: phone,
            funds: funds,
            total_leads: total_leads,
            daily_leads: daily_leads,
            action_price: action_price,
            password: password,
            countries: countries,
            password_confirmation: password_confirmation,
            quality_score_target_from: quality_score_target_from,
            quality_score_target_to: quality_score_target_to,
            "_token": "{{ csrf_token() }}",
        };
        $.ajax({
            url: '/users',
            type: 'POST',
            data: data,
            success: function(data) {
                 $("#error").hide();
                if (data.success === 201) {
                    
                    $("#alert").text("User created successfully!.");
                } else {
                    
                    $("#alert").text("Error while creating user!.");
                }
                window.animateToTop("alert");
                $("#alert").show();
            },
            error: function(data) {
                errorsHtml = "";
                $("#alert").hide();
                $.each(data.responseJSON.errors, function(key, value) {
                    errorsHtml += '<li>' + value[0] + '</li>'; //showing only the first error.
                });
                $("#error").html(errorsHtml);
                window.animateToTop("error");
                $("#error").show();
            }
        });
    });
});
</script>
@endsection

resources/views/user/export.blade.php
<table class="table">
<thead>
<tr>
    <th>Id</th>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Targeted Countries</th>
    <th>Funds</th>
    <th>Daily leads</th>
    <th>Total leads</th>
    <th>Action Price (CPL-CPA)</th>
    <th>Target Quality Score From</th>
    <th>Target Quality Score To</th>
    <th>Created At</th>
</tr>
</thead>
<tbody>
    @foreach($users as $user)   
    <tr>
    <td>{{$user->id}}</td>
    <td>{{$user->name}}</td>
    <td>{{$user->email}}</td>
    <td>{{$user->phone}}</td>
    <td>
    @foreach($user->countries as $country)
        <p>{{$country->name}}</p>
    @endforeach
    </td>
    <td>{{$user->funds}}</td>
    <td>{{$user->daily_leads}}</td>
    <td>{{$user->total_leads}}</td>
    <td>{{$user->action_price}}</td>
    <td>{{$user->quality_score_target_from}}</td>
    <td>{{$user->quality_score_target_to}}</td>
    <td>{{$user->created_at}}</td>

    </tr>
    @endforeach
</tbody>
</table>



<script type="text/javascript">
  (function(){
          window.print();
  })();
</script>

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                @if(auth()->user()->is_admin)
                    @include('admin.users-table')
                @endif
                    @include('lead.lead-table')
            
            
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/info.blade.php
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">Account Information</div>
            <div class="card-body">
               <p> <strong>Name:</strong>  {{auth()->user()->name}}</p> 
               <p> <strong>Email:</strong> {{auth()->user()->email}}</p> 
               <p> <strong>Phone:</strong> {{auth()->user()->phone}}</p> 
               <p> <strong>Date of registration:</strong> {{auth()->user()->created_at}} ({{auth()->user()->created_at->diffForHumans()}})</p> 
               <p> <strong>Total Leads:</strong> {{auth()->user()->total_leads}}</p> 
               <p> <strong>Countries:</strong> 
                @foreach(auth()->user()->countries as $country)
                
                    <span class="badge badge-success">{{$country->name}}</span>
                @endforeach
               </p> 

            @if(auth()->user()->can_see_all_information)
               <p> <strong>Daily Leads:</strong> {{auth()->user()->daily_leads}}</p> 
               <p> <strong>Funds:</strong> {{auth()->user()->funds}}</p> 
               <p> <strong>Action Price:</strong> {{auth()->user()->action_price}}</p> 
            @endif
            </div>
        </div>
    </div>
</div>

resources/views/user/message.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Messages From The System</div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Date</th>
                                <th>Message</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($messages as $message)
                            <tr>
                                <td>{{$message->id}}</td>
                                <td>{{$message->created_at->diffForHumans()}}</td>
                                <td>{{$message->message}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $messages->links() }}
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row justify-content-center">
        
        <div class="alert alert-success" style="display:none" id="alert" role="alert">
        </div>
        <div class="alert alert-danger" style="display:none" id="error" role="alert">
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Send a Message</div>
                <div class="card-body">
                    <form class="form">
                        <input type="hidden" id='user' value="{{$admin->id}}" />
                        <div class="form-group">
                            <label for="message">Message</label>
                            <textarea type="message" class="form-control" placeholder="Write a message.." id="message"></textarea>
                        </div>
                        <button type="button" id="user-send-message" class="btn btn-default">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    <script>
    
$(document).ready(function() {

    $("#alert").css('display', 'none');
    $("#user-send-message").click(function(e) {
        var userId = $("#user").val();
        var message = $("#message").val();

        var data = {
            to: userId,
            message: message,
            "_token": "{{ csrf_token() }}",
        };
        $.ajax({
            url: '/messages/'+userId,
            type: 'POST',
            data: data,
            success: function(data) {
                $("#error").hide();
                if (data.success === 200) {
                    $("#alert").text("Message sent successfully!.");
                } else {
                    $("#alert").text("Error while sending the message!.");
                }
                window.animateToTop("alert");
                $("#alert").show();
            },
            error: function(data) {
                $("#alert").hide();
                errorsHtml = "";
                $.each(data.responseJSON.errors, function(key, value) {
                    errorsHtml += '<li>' + value[0] + '</li>'; //showing only the first error.
                });
                $("#error").html(errorsHtml);
                window.animateToTop("error");
                $("#error").show();
            }
        });
    });
});
</script>

@endsection

resources/views/user/send-message.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        
        <div class="alert alert-success" style="display:none" id="alert" role="alert">
        </div>
        <div class="alert alert-danger" style="display:none" id="error" role="alert">
        </div>
        <div class="col-md-12">
            <form class="form">
                <input type="hidden" name="user_id" value="{{$admin->id}}" />
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea type="message" class="form-control" placeholder="Write a message.." id="message"></textarea>
                </div>
                <button type="button" id="send-message" class="btn btn-default">Send</button>
            </form>
        </div>
    </div>
</div>
<script>
    
$(document).ready(function() {

    $('#user').select2();
    $("#alert").css('display', 'none');
    $("#send-message").click(function(e) {
        var userId = $("#user").val();
        var message = $("#message").val();

        var data = {
            user_id: userId,
            message: message,
            "_token": "{{ csrf_token() }}",
        };
        $.ajax({
            url: '/messages/'+userId,
            type: 'POST',
            data: data,
            success: function(data) {
                $("#error").hide();
                if (data.success === 201) {
                    $("#alert").text("Message sent successfully!.");
                } else {
                    $("#alert").text("Error while sending the message!.");
                }
                window.animateToTop("alert");
                $("#alert").show();
            },
            error: function(data) {
                $("#alert").hide();
                errorsHtml = "";
                $.each(data.responseJSON.errors, function(key, value) {
                    errorsHtml += '<li>' + value[0] + '</li>'; //showing only the first error.
                });
                $("#error").html(errorsHtml);
                window.animateToTop("error");
                $("#error").show();
            }
        });
    });
});
</script>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        

        <div class="alert alert-success" style="display:none" id="alert" role="alert">

        </div>

        <div class="alert alert-danger" style="display:none" id="error" role="alert">
        </div>
            <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="name">Allow partner to see all information:</label>
                <input type="checkbox" id="can-see-all-information" @if($user->can_see_all_information) checked @endif aria-label="Checkbox for following text input">
            </div>
        </div>
    </div>
        <div class="col-md-12">
            <form class="form"  action="{{route('users.update',$user->id)}}">
                <input type="hidden" value="{{$user->id}}" id="user_id">
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" id="name" value="{{$user->name}}">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" value="{{$user->email}}" id="email">
                </div>

                <div class="form-group">
                    <label for="countries">Countries</label>
                        
                       

                    <select id="countries" class="form-control" multiple>
                        @foreach($countries as $country)
                    
                            @if(in_array($country->name,$user->countries()->pluck('name')->toArray()))
                                <option selected value="{{$country->id}}">{{$country->name}}</option>
                            @else
                                <option value="{{$country->id}}">{{$country->name}}</option>
                            @endif
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="name">Phone:</label>
                    <input type="text" class="form-control" value="{{$user->phone}}" id="phone">
                </div>
                <div class="form-group">
                    <label for="funds">Funds:</label>
                    <input type="number" class="form-control" value="{{$user->funds}}" id="funds">
                </div>
                <div class="form-group">
                    <label for="total_leads">Total Leads:</label>
                    <input type="number" class="form-control" value="{{$user->total_leads}}" id="total_leads">
                </div>
                
                <div class="form-group">
                    <label for="daily_leads">Daily Leads:</label>
                    <input type="number" class="form-control" value="{{$user->daily_leads}}" id="daily_leads">
                </div>
                
                <div class="form-group">
                    <label for="action_price">Action Price:</label>
                    <input type="number" class="form-control" value="{{$user->action_price}}" id="action_price">
                </div>

                <div class="form-group">
                    <label for="quality_score_target_from">Targeted Quality Score From:</label>
                    <input type="text" class="form-control" value="{{$user->quality_score_target_from}}" id="quality_score_target_from">
                </div>

                 <div class="form-group">
                    <label for="quality_score_target_to">Targeted Quality Score To:</label>
                    <input type="text" class="form-control" value="{{$user->quality_score_target_to}}" id="quality_score_target_to">
                </div>


                <button type="button" id="update-user" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>
</div>

<script sync>
    $(document).ready(function(){

        $('#countries').select2();
        $("#alert").css('display','none');
        $("#can-see-all-information").change(function(e){
            var data = {
                status:this.checked===true?1:0,
                "_token": "{{ csrf_token() }}",    
            };
            var id = $("#user_id").val();
            var successMessage = this.checked === true? "User can see all information.":"User can't see all information.";
            $.ajax({
                url: '/users/information-visibility/'+ id,
                type: 'POST',
                data: data,
                success: function(data) {
                    if(data.success === 200){
                        $("#alert").text(successMessage);
                    }else{
                        $("#alert").text("Error while updating user!.");
                    }
                    window.animateToTop("alert");

                    $("#alert").show();
                },
                error:function(data){

                    errorsHtml ="";
                    $.each( data.responseJSON.errors, function( key, value ) {

                        errorsHtml += '<li>' + value[0] + '</li>'; //showing only the first error.
                    });
                     $("#error").html(errorsHtml);
                    window.animateToTop("error");
                      $("#error").show();
                }
            });
        });

        $("#update-user").click(function(e){
        var id = $("#user_id").val();
        var name = $("#name").val();
        var email = $("#email").val();
        var phone = $("#phone").val();
        var funds = $("#funds").val();
        var countries = $("#countries").val();  
        var total_leads = $("#total_leads").val();
        var daily_leads = $("#daily_leads").val();
        var daily_leads = $("#daily_leads").val();
        var action_price = $("#action_price").val();
        var quality_score_target_from = $("#quality_score_target_from").val();
        var quality_score_target_to = $("#quality_score_target_to").val();
            var data = {
                name:name,
                email:email,
                phone:phone,
                funds:funds,
                countries:countries,
                total_leads:total_leads,
                daily_leads:daily_leads,
                action_price:action_price,
                quality_score_target_from:quality_score_target_from,
                quality_score_target_to:quality_score_target_to,
                "_token": "{{ csrf_token() }}",    
            };

            $.ajax({
                url: '/users/'+ id,
                type: 'PUT',
                data: data,
                success: function(data) {
                    if(data.success === 204){
                        $("#alert").text("User updated successfully!.");

                    }else{
                        $("#alert").text("Error while updating user!.");
                    }
                    window.animateToTop("alert");

                    $("#alert").show();
                },
                error:function(data){

                    errorsHtml ="";
                    $.each( data.responseJSON.errors, function( key, value ) {

                        errorsHtml += '<li>' + value[0] + '</li>'; //showing only the first error.
                    });
                     $("#error").html(errorsHtml);
                    window.animateToTop("error");
                      $("#error").show();
                }
            });
        }); 
    });
</script>
@endsection